### ISSUE TITLE
update helm repos does not work

### ISSUE THREAD

**Issue by vonDowntown** [istvano/ansible_role_microk8s#12]
```
TASK [istvano.microk8s : update helm repos] ***************************************************************************************************************************************************************
failed: [cloud01] (item=ubuntu) => {"ansible_loop_var": "user", "changed": false, "msg": "missing required arguments: release_name, release_namespace", "user": "ubuntu"}
failed: [cloud04] (item=ubuntu) => {"ansible_loop_var": "user", "changed": false, "msg": "missing required arguments: release_name, release_namespace", "user": "ubuntu"}
failed: [cloud03] (item=ubuntu) => {"ansible_loop_var": "user", "changed": false, "msg": "missing required arguments: release_name, release_namespace", "user": "ubuntu"}
failed: [cloud02] (item=ubuntu) => {"ansible_loop_var": "user", "changed": false, "msg": "missing required arguments: release_name, release_namespace", "user": "ubuntu"}
``` 
A more detailed log:  
```
failed: [cloud01] (item=ubuntu) => {
    "ansible_loop_var": "user",
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "atomic": false,
            "binary_path": null,
            "ca_cert": null,
            "chart_ref": null,
            "chart_repo_url": null,
            "chart_version": null,
            "context": null,
            "create_namespace": false,
            "disable_hook": false,
            "force": false,
            "host": null,
            "kubeconfig": null,
            "purge": true,
            "release_name": null,
            "release_namespace": null,
            "release_state": "present",
            "release_values": {},
            "replace": false,
            "skip_crds": false,
            "update_cache": true,
            "update_repo_cache": false,
            "validate_certs": true,
            "values_files": [],
            "wait": false,
            "wait_timeout": null
        }
    },
    "msg": "missing required arguments: release_name, release_namespace",
    "user": "ubuntu"
}
```

As stated in the message release_name and release_namespace are required.
If you look at the current doku at https://docs.ansible.com/ansible/latest/collections/community/kubernetes/helm_module.html
you will see that from now on they are required.

I will prepare a fix and create a merge request.

If you have some remarks feel free to comment ^^
I'm pretty new to kubernetes, so every comment if i am doing something wrong is appreciated.

**Comment by vonDowntown** [comment]
I digged into https://github.com/ansible-collections/kubernetes.core/blob/main/plugins/modules/helm.py
as far as i am concerned this should work.
It's a real bummer that the old version does not work anymore.

**Comment by vonDowntown** [comment]
Another way would be changing 
``` 
- name: add helm repository to user
  become: yes
  become_user: '{{ user }}'
  community.kubernetes.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
  when: microk8s_plugin_helm3_enable
  ``` 
  to(untested):
  ``` 
  - name: add helm repository to user
  become: yes
  become_user: '{{ user }}'
  community.kubernetes.helm:
    name: stable
    namespace: default
    repo_url: https://charts.helm.sh/stable
    update_repo_cache: yes
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
  when: microk8s_plugin_helm3_enable
  ```
  This would include a the update command prior to the add which should be idempotent to adding and upgrading.
