### ISSUE TITLE
Microk8s Version upgrade does not work

### ISSUE THREAD

**Issue by vonDowntown** [istvano/ansible_role_microk8s#16]
Expected Behaviour: Changing 'microk8s_version'  would change the version of the installed microk8s.

What happens: Version is still on v1.19

my current by hand fix was running `sudo snap refresh microk8s --channel=latest/stable ` on all servers.

**Comment by istvano** [comment]
Hi, 

you can specify the version by providing microk8s_version: "1.19/stable"
see the 
https://github.com/istvano/ansible_role_microk8s/blob/master/defaults/main.yml

**Comment by vonDowntown** [comment]
Yes i tried that multiple times. Ansible just printed ok: ...
so no change was detected

**Comment by adamcstephens** [comment]
From my testing, the role won't change the version of the channel after initial install. I used the following tasks to switch channels (but not force a refresh)

```
    - name: get snap channel
      shell:
        cmd: snap list --unicode=never microk8s | grep microk8s | awk '{print $4}'
      register: snap_version
      changed_when: false

    - name: update snap channel
      command:
        cmd: snap switch microk8s --channel={{ microk8s_version }}
      become: true
      when:
        - snap_version.stdout != microk8s_version
```
