### ISSUE TITLE
Task `reaffirm permission on files` not working?

### ISSUE THREAD

**Issue by mosgjig** [istvano/ansible_role_microk8s#41]
I'm having an issue where this portion of `configure-groups.yml` doesn't do what I think it's supposed to do.

```
- name: reaffirm permission on files
  become: yes
  file:
    path: ~/.kube
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    recurse: yes
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
```

The playbook to execute the role:
```
- hosts: cluster
  gather_subset:
    - all_ipv4_addresses

- hosts: cluster
  # serial: 1
  gather_facts: yes
  roles:
    - role: istvano.microk8s
      become: true
      vars:
        users:
          - ubuntu
        microk8s_version: stable
        microk8s_enable_HA: true
        microk8s_group_HA: cluster
```

Verifying ownership of `~/.kube/config`

```
$ ansible cluster -i inventories/microk8s/hosts -m shell -a "ls -lh ~/.kube/"
pi | CHANGED | rc=0 >>
total 8.0K
drwxr-x--- 4 ubuntu ubuntu 4.0K Jan 18 14:24 cache
-rw-r--r-- 1 root   root   1.9K Jan 20 13:17 config
pi-2 | CHANGED | rc=0 >>
total 4.0K
-rw-r--r-- 1 root root 105 Jan 20 13:18 config
pi-1 | CHANGED | rc=0 >>
total 4.0K
-rw-r--r-- 1 root root 105 Jan 20 13:18 config
```

One would assume that config would be owned by `ubuntu:ubuntu`

Any suggestions?
