### ISSUE TITLE
can not enable snap auto update after disabled it

### ISSUE THREAD

**Issue by zerr0s** [istvano/ansible_role_microk8s#44]
Hello,

I have successfully installed microk8s using this role, with the snap auto update to false.
After that I have put this variable to true dans I can see an entry in the host file:
```
microk8s_disable_snap_autoupdate: true
```
```
# BEGIN ANSIBLE MANAGED: microk8s Disable snap autoupdate
127.0.0.1 api.snapcraft.io
# END ANSIBLE MANAGED: microk8s Disable snap autoupdate
```

If I want to enable the snap auto update, there is no task to remove the host entry. Something like this should works:

```
microk8s_disable_snap_autoupdate: false
```

```yaml
- name: Disable snap autoupdate
  become: true
  blockinfile:
    state: "{{ 'present' if microk8s_disable_snap_autoupdate == true else 'absent' }}"
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: microk8s Disable snap autoupdate"
    content: |
      127.0.0.1 api.snapcraft.io
```
