### ISSUE TITLE
Inventory example

### ISSUE THREAD

**Issue by metabsd** [istvano/ansible_role_microk8s#5]
Hi, can you share an example of your inventory please to better understand the HA section.
Good job👍

**Comment by istvano** [comment]
Hi,

@eshikhov Do you think you could add an example section to the README how you set up your own HA?

btw: Thanks for adding that feature!

**Comment by eshikhov** [comment]
enable the parameter

microk8s_enable_HA: true

add a group with hosts to the inventory file

[microk8s_HA]
node1
node2
node3

if you don't like the name of the group microk8s_HA, you can redefine it in the variable microk8s_group_HA for example microk8s_group_HA: "k8s_HA"
[k8s_HA]
node1
node2
node3

**Comment by metabsd** [comment]
Would be great to support pod code, service cidr custom. Using an external load balancer. Etc...

**Comment by istvano** [comment]
Thanks for adding your example

**Comment by istvano** [comment]
@metabsd Do you think you could add something like that?

**Comment by terala** [comment]
This `inventory.yaml` works for me:
```yaml
all:
    multinode_cluster:
      children:
        microk8s_HA:
          hosts:
            node3:
            node4:
            node5:
        microk8s_WORKERS:
          hosts:
            node1:
            node2:

    k8s:
      children:
        single_node_clusters:
        multinode_cluster:

```
