### ISSUE TITLE
Failing on second run with no attribute 'addons'

### ISSUE THREAD

**Issue by peterfortuin** [istvano/ansible_role_microk8s#51]
I have deployed my microk8s cluster without any problems, but when I run my playbook for the second time I get this error:

```shell
fatal: [node2]: FAILED! => {"msg": "'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'addons'"}
```

This is a part of my playbook:

```yaml
roles:
    - role: 'istvano.microk8s'
      vars:
        microk8s_version: "1.31/stable"
        microk8s_dns_resolvers: <ip range>
        microk8s_enable_HA: false
        microk8s_group_HA: "home_cluster_master"
        microk8s_group_WORKERS: "home_cluster_workers"
        users: [ubuntu]
        add_workers_to_hostfile: false
        microk8s_plugins:
          dns: "{{ microk8s_dns_resolvers }}"     # CoreDNS
          host-access: false                      # Allow Pods connecting to Host services smoothly
          ingress: true                           # Ingress controller for external access
          metrics-server: false                   # K8s Metrics Server for API access to service metrics
          rbac: false                             # Role-Based Access Control for authorisation
          hostpath-storage: false                 # Storage class; allocates storage from host directory
          registry: false                         # Private image registry exposed on localhost:32000
          dashboard: false                        # The Kubernetes dashboard
          ambassador: false                       # Ambassador API Gateway and Ingress
          cilium: false                           # SDN, fast with full network policy
          fluentd: false                          # Elasticsearch-Fluentd-Kibana logging and monitoring
          gpu: false                              # Automatic enablement of Nvidia CUDA
          helm: false                             # Helm 2 - the package manager for Kubernetes
          helm3: true                             # Helm 3 - Kubernetes package manager
          istio: false                            # Core Istio service mesh services
          jaeger: false                           # Kubernetes Jaeger operator with its simple config
          knative: false                          # The Knative framework on Kubernetes.
          kubeflow: false                         # Kubeflow for easy ML deployments
          linkerd: false                          # Linkerd is a service mesh for Kubernetes and other frameworks
          metallb: false                          # Loadbalancer for your Kubernetes cluster
          multus: false                           # Multus CNI enables attaching multiple network interfaces to pods
          prometheus: false                       # Prometheus operator for monitoring and logging
          traefik: false                          # another ingress
          portainer: false                        # Container management dashboard
          keda: false                             # Kubernetes Event-driven Autoscaling operator.
          kata: false                             # A secure container runtime with lightweight virtual machines
          openebs: false                          # openebs storage
          openfaas: false                         # serverless
```
